import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from './components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-gray-100  ${inter.className}`}>
        <div className="relative z-20"><Navbar /></div>
        <div className="w-full md:w-[80%] mx-auto px-4 lg:px-0 min-h-[90vh]">
          {children}
        </div>
      </body>
    </html>
  );
}
